name              'maven'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Custom resources for installing Apache Maven and downloading Maven artifacts'
version           '7.0.0'
source_url        'https://github.com/sous-chefs/maven'
issues_url        'https://github.com/sous-chefs/maven/issues'
chef_version      '>= 16.0'

depends 'ark', '>= 5.0'

supports 'almalinux', '>= 8.0'
supports 'amazon',    '>= 2023.0'
supports 'debian',    '>= 12.0'
supports 'fedora'
supports 'rocky',     '>= 8.0'
supports 'ubuntu',    '>= 22.04'
