name              'maven'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs Apache Maven includes a resource for installing artifacts from maven'
version           '6.0.10'
source_url        'https://github.com/sous-chefs/maven'
issues_url        'https://github.com/sous-chefs/maven/issues'
chef_version      '>= 15.3'

depends 'ark',  '>= 1.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
supports 'windows'
